/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── All colors now read from CSS variables ──
           Dark values set on :root (default)
           Light values set on html.light (overrides)           */
        background:                  "var(--color-background)",
        surface:                     "var(--color-surface)",
        "surface-dim":               "var(--color-surface-dim)",
        "surface-bright":            "var(--color-surface-bright)",
        "surface-container-lowest":  "var(--color-surface-container-lowest)",
        "surface-container-low":     "var(--color-surface-container-low)",
        "surface-container":         "var(--color-surface-container)",
        "surface-container-high":    "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-variant":           "var(--color-surface-variant)",
        "surface-tint":              "var(--color-surface-tint)",
        "on-background":             "var(--color-on-background)",
        "on-surface":                "var(--color-on-surface)",
        "on-surface-variant":        "var(--color-on-surface-variant)",
        "outline":                   "var(--color-outline)",
        "outline-variant":           "var(--color-outline-variant)",
        "outline-muted":             "var(--color-outline-muted)",
        "primary":                   "var(--color-primary)",
        "on-primary":                "var(--color-on-primary)",
        "primary-container":         "var(--color-primary-container)",
        "on-primary-container":      "var(--color-on-primary-container)",
        "primary-fixed":             "var(--color-primary-fixed)",
        "primary-fixed-dim":         "var(--color-primary-fixed-dim)",
        "on-primary-fixed":          "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant":  "var(--color-on-primary-fixed-variant)",
        "inverse-primary":           "var(--color-inverse-primary)",
        "secondary":                 "var(--color-secondary)",
        "on-secondary":              "var(--color-on-secondary)",
        "secondary-container":       "var(--color-secondary-container)",
        "on-secondary-container":    "var(--color-on-secondary-container)",
        "tertiary":                  "var(--color-tertiary)",
        "on-tertiary":               "var(--color-on-tertiary)",
        "tertiary-container":        "var(--color-tertiary-container)",
        "on-tertiary-container":     "var(--color-on-tertiary-container)",
        "error":                     "var(--color-error)",
        "on-error":                  "var(--color-on-error)",
        "error-container":           "var(--color-error-container)",
        "on-error-container":        "var(--color-on-error-container)",
        "error-red":                 "var(--color-error-red)",
        "success-green":             "#22c55e",
        "inverse-surface":           "var(--color-inverse-surface)",
        "inverse-on-surface":        "var(--color-inverse-on-surface)",
        "surface-glass":             "rgba(45, 52, 73, 0.4)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
