/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#222a3d",
        "on-secondary-container": "#c9aeff",
        "on-tertiary-fixed-variant": "#793100",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-container": "#ffe0d2",
        "surface-container": "#171f33",
        "outline-variant": "#444654",
        secondary: "#d2bbff",
        "surface-container-low": "#131b2e",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed": "#25005a",
        "surface-dim": "#0b1326",
        "tertiary-fixed": "#ffdbcb",
        tertiary: "#ffb691",
        "inverse-on-surface": "#283044",
        "on-surface": "#dae2fd",
        "primary-container": "#3b5bdb",
        "tertiary-container": "#ac4900",
        "surface-bright": "#31394d",
        background: "#0b1326",
        "secondary-fixed": "#eaddff",
        "on-surface-variant": "#c4c5d6",
        "on-tertiary": "#552000",
        error: "#ffb4ab",
        "primary-fixed": "#dde1ff",
        "on-primary-container": "#e2e5ff",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-secondary": "#3f008e",
        "surface-variant": "#2d3449",
        "on-primary": "#002388",
        "inverse-surface": "#dae2fd",
        primary: "#b8c3ff",
        "on-background": "#dae2fd",
        "inverse-primary": "#3052d2",
        outline: "#8e90a0",
        "on-primary-fixed-variant": "#0736ba",
        "secondary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#001355",
        "surface-tint": "#b8c3ff",
        "error-container": "#93000a",
        surface: "#0b1326",
        "on-tertiary-fixed": "#341100",
        "surface-container-lowest": "#060e20",
        "primary-fixed-dim": "#b8c3ff",
        "secondary-container": "#6001d1",
        "on-error": "#690005",
        "error-red": "#ffb4ab",
        "success-green": "#22c55e",
        "outline-muted": "rgba(255, 255, 255, 0.1)",
        "surface-glass": "rgba(45, 52, 73, 0.4)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
